### ISSUE TITLE
New languages needed!

### ISSUE THREAD

**Issue by virejdasani** [virejdasani/FizzBuzz-EVERYTHING#7]
Add fizzbuzz.<newlanguage> to be a contributor in this repo. The goal is to get every single language into this repo!

**Comment by Paolo-Cosentino** [comment]
Just submitted a PR for examples in Lua and C++.

**Comment by virejdasani** [comment]
Thanks very much! You are now officially a contributor of [FizzBuzz-EVERYTHING](https://github.com/virejdasani/FizzBuzz-EVERYTHING) 👍

**Comment by Mystic-Developer** [comment]
Just submitted a Mips version of FizzBuzz
